### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by jasenj1** [eugene-kamenev/orientdb-groovy#24]
Sorry for a very clueless issue, but I'm starting a project using OrientDB and I'd like to use Grails for my web front-end. Can you point me to any documentation that would get me started using your datastore extension? I looked at the Neo4J one, but they have a "plugin" and I don't know how (or even if I can) use the raw datastore extension without a plugin.

**Comment by eugene-kamenev** [comment]
Hi,

I created this project for educational purposes, it is better now to give a
try for OrientDB GORM implementation, that I am trying to implement. Much
work already done, many native GORM tests passed, but it is also not
production ready. I need some help to finish it, having time issues for
open source contributions.

Here is the link:

https://github.com/eugene-kamenev/grails-data-mapping
15 апр. 2016 г. 10:36 PM пользователь "Jasen Jacobsen" <
notifications@github.com> написал:

**Comment by eugene-kamenev** [comment]
@jasenj1 any success with it?

**Comment by jasenj1** [comment]
Sorry, I called pulled in other directions by other projects.
I was thinking of just ignoring GORM and creating an OrientDB bean and working with it natively.
I was in a situation where if I could slap together a quick demo of Grails working with OrientDB that would look good to my management. It turned into real work - i.e. time - so it got pushed to the side.
- Jasen.

**Comment by crazy4groovy** [comment]
+1 for working natively with OrientDb :smiley:
